export const config = {
  appName: 'AllSearch',
  appDescription: "Make Your Agency's AI SEO Service Scale Across Every Client Account",
  // SEO keywords for the project site (issue 23). Not used by the app itself.
  keywords: [
    'allsearch',
    'all search',
    'generative engine optimization',
    'GEO analytics',
    'AI search traffic',
    'AI search visibility',
    'ChatGPT SEO',
    'Perplexity optimization',
    'Google AI Mode',
    'generative search optimization',
    'AI engine ranking',
    'AI citation tracking',
    'ChatGPT ranking',
    'Gemini optimization',
    'AI search analytics',
    'generative AI optimization',
    'AI visibility dashboard',
    'prompt intelligence',
    'competitor AI tracking',
    'AI search performance',
    'LLM optimization',
    'AI engine visibility',
    'generative search traffic',
    'AI search marketing',
    'content optimization AI engines',
    'AI search competitor analysis',
    'brand visibility AI',
    'AI search monitoring',
    'GEO opportunities',
    'AI engine analytics',
  ],
  colors: {
    // Reflected on the whole app outside of the document (loading bar, Chrome tabs, etc..)
    main: 'var(--color-brand-500)', // #55c891
  },
};