export type DomainCategory = 'You' | 'UGC' | 'Institutional' | 'Editorial' | 'Other';

export const DOMAIN_CATEGORIES: Record<string, DomainCategory> = {
  // UGC (User Generated Content)
  'reddit.com': 'UGC',
  'facebook.com': 'UGC',
  'twitter.com': 'UGC',
  'x.com': 'UGC',
  'linkedin.com': 'UGC',
  'instagram.com': 'UGC',
  'tiktok.com': 'UGC',
  'youtube.com': 'UGC',
  'pinterest.com': 'UGC',
  'tumblr.com': 'UGC',
  'snapchat.com': 'UGC',
  'quora.com': 'UGC',
  'medium.com': 'UGC',
  'stackoverflow.com': 'UGC',
  'github.com': 'UGC',
  'gitlab.com': 'UGC',
  'twitch.tv': 'UGC',
  'discord.com': 'UGC',
  'vimeo.com': 'UGC',
  'yelp.com': 'UGC',
  'tripadvisor.com': 'UGC',
  'glassdoor.com': 'UGC',
  'behance.net': 'UGC',
  'dribbble.com': 'UGC',
  'flickr.com': 'UGC',
  'whatsapp.com': 'UGC',
  'telegram.org': 'UGC',
  'deviantart.com': 'UGC',
  'goodreads.com': 'UGC',
  'wattpad.com': 'UGC',
  '9gag.com': 'UGC',
  'imgur.com': 'UGC',
  'patreon.com': 'UGC',
  'substack.com': 'UGC',
  'producthunt.com': 'UGC',
  'hackernews.com': 'UGC', // news.ycombinator.com often referred to as this
  'ycombinator.com': 'UGC',
  'dev.to': 'UGC',
  'hashnode.com': 'UGC',

  // Institutional (Governments, Organizations, Wikis)
  'wikipedia.org': 'Institutional',
  'en.wikipedia.org': 'Institutional',
  'wikimedia.org': 'Institutional',
  'archive.org': 'Institutional',
  'un.org': 'Institutional', // United Nations
  'who.int': 'Institutional', // WHO
  'wto.org': 'Institutional', // WTO
  'imf.org': 'Institutional', // IMF
  'worldbank.org': 'Institutional',
  'europa.eu': 'Institutional', // EU
  'nato.int': 'Institutional',
  'oecd.org': 'Institutional',
  'weforum.org': 'Institutional', // World Economic Forum
  'nasa.gov': 'Institutional',
  'nih.gov': 'Institutional',
  'cdc.gov': 'Institutional',
  'noaa.gov': 'Institutional',
  'whitehouse.gov': 'Institutional',
  'usa.gov': 'Institutional',
  'state.gov': 'Institutional',
  'fbi.gov': 'Institutional',
  'gov.uk': 'Institutional',
  'canada.ca': 'Institutional',
  'australia.gov.au': 'Institutional',
  'india.gov.in': 'Institutional',
  'mofa.go.jp': 'Institutional',
  'bundesregierung.de': 'Institutional',
  'harvard.edu': 'Institutional',
  'mit.edu': 'Institutional',
  'stanford.edu': 'Institutional',
  'ox.ac.uk': 'Institutional',
  'cam.ac.uk': 'Institutional',
  'yale.edu': 'Institutional',
  'columbia.edu': 'Institutional',
  'princeton.edu': 'Institutional',
  'berkeley.edu': 'Institutional',
  'cornell.edu': 'Institutional',
  'khanacademy.org': 'Institutional',
  'coursera.org': 'Institutional',
  'edx.org': 'Institutional',
  'ted.com': 'Institutional',

  // Editorial (News, Magazines, Publications)
  'nytimes.com': 'Editorial',
  'wsj.com': 'Editorial',
  'washingtonpost.com': 'Editorial',
  'bbc.com': 'Editorial',
  'bbc.co.uk': 'Editorial',
  'cnn.com': 'Editorial',
  'reuters.com': 'Editorial',
  'apnews.com': 'Editorial',
  'bloomberg.com': 'Editorial',
  'ft.com': 'Editorial', // Financial Times
  'economist.com': 'Editorial',
  'guardian.com': 'Editorial',
  'theguardian.com': 'Editorial',
  'dailymail.co.uk': 'Editorial',
  'independent.co.uk': 'Editorial',
  'telegraph.co.uk': 'Editorial',
  'usatoday.com': 'Editorial',
  'latimes.com': 'Editorial',
  'nypost.com': 'Editorial',
  'foxnews.com': 'Editorial',
  'nbcnews.com': 'Editorial',
  'cbsnews.com': 'Editorial',
  'abcnews.go.com': 'Editorial',
  'msnbc.com': 'Editorial',
  'huffpost.com': 'Editorial',
  'buzzfeed.com': 'Editorial',
  'vice.com': 'Editorial',
  'vox.com': 'Editorial',
  'theverge.com': 'Editorial',
  'wired.com': 'Editorial',
  'techcrunch.com': 'Editorial',
  'arstechnica.com': 'Editorial',
  'engadget.com': 'Editorial',
  'gizmodo.com': 'Editorial',
  'cnet.com': 'Editorial',
  'zdnet.com': 'Editorial',
  'forbes.com': 'Editorial',
  'fortune.com': 'Editorial',
  'businessinsider.com': 'Editorial',
  'cnbc.com': 'Editorial',
  'marketwatch.com': 'Editorial',
  'barrons.com': 'Editorial',
  'politico.com': 'Editorial',
  'axios.com': 'Editorial',
  'thehill.com': 'Editorial',
  'slate.com': 'Editorial',
  'salon.com': 'Editorial',
  'theatlantic.com': 'Editorial',
  'newyorker.com': 'Editorial',
  'time.com': 'Editorial',
  'newsweek.com': 'Editorial',
  'vanityfair.com': 'Editorial',
  'vogue.com': 'Editorial',
  'gq.com': 'Editorial',
  'esquire.com': 'Editorial',
  'elle.com': 'Editorial',
  'cosmopolitan.com': 'Editorial',
  'people.com': 'Editorial',
  'usmagazine.com': 'Editorial',
  'rollingstone.com': 'Editorial',
  'variety.com': 'Editorial',
  'hollywoodreporter.com': 'Editorial',
  'deadline.com': 'Editorial',
  'billboard.com': 'Editorial',
  'pitchfork.com': 'Editorial',
  'ign.com': 'Editorial',
  'gamespot.com': 'Editorial',
  'polygon.com': 'Editorial',
  'kotaku.com': 'Editorial',
  'eurogamer.net': 'Editorial',
  'aljazeera.com': 'Editorial',
  'dw.com': 'Editorial',
  'france24.com': 'Editorial',
  'scmp.com': 'Editorial', // South China Morning Post
  'japantimes.co.jp': 'Editorial',
  'straitstimes.com': 'Editorial',
  'timesofindia.indiatimes.com': 'Editorial',
  'hindustantimes.com': 'Editorial',
  'rt.com': 'Editorial',
  'sputniknews.com': 'Editorial',
  'npr.org': 'Editorial',
  'pbs.org': 'Editorial',
  'nationalgeographic.com': 'Editorial',
  'scientificamerican.com': 'Editorial',
  'newscientist.com': 'Editorial',
  'nature.com': 'Editorial',
  'sciencemag.org': 'Editorial',
  'thesun.co.uk': 'Editorial',
};

export function getDomainCategory(sourceHostname: string, projectHostname: string): DomainCategory {
  if (sourceHostname === projectHostname) return 'You';
  return DOMAIN_CATEGORIES[sourceHostname] ?? 'Other';
}

export function isDomainCategory(hostname: string, category: DomainCategory): boolean {
  return DOMAIN_CATEGORIES[hostname] === category;
}
